spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173, http://localhost:5174, http://localhost:5175"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      default-filters:
        - FiltroAutenticacion

server:
  port: 8766
